uploads = []
generated = []

[[outputs]]
id = "Xee38PzHzeMMHL5F2-yPp"
uri = "file://output/Library_Management_System_Presentation.pptx"
type = "slides"
title = "Library Management System — Hinglish Presentation (12 Slides)"

[[outputs]]
id = "lfWR8DshmcpMYEL4RBDTH"
uri = "file://output/Library_Management_System_Documentation.docx"
type = "word_document"
title = "Library Management System — Comprehensive Documentation Report (90+ Pages, Hinglish)"

[[outputs]]
id = "avNUCtyXwQo6wWAmQM0sl"
uri = "file://assets/login_banner_light.png"
type = "image"
title = "Library Banner (Light Theme)"

[[outputs]]
id = "QOMgWuG6y9ImLzOr21eSw"
uri = "file://assets/login_banner_dark.png"
type = "image"
title = "Library Banner (Dark Theme)"
